apiVersion: v1
kind: Service
metadata:
  name: consul
  namespace: crypto-staking
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8500
      targetPort: 8500
    - name: dns
      port: 8600
      targetPort: 8600
      protocol: UDP
  selector:
    app: consul
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: consul
  namespace: crypto-staking
spec:
  serviceName: consul
  replicas: 3
  selector:
    matchLabels:
      app: consul
  template:
    metadata:
      labels:
        app: consul
    spec:
      containers:
      - name: consul
        image: consul:latest
        ports:
        - containerPort: 8500
          name: http
        - containerPort: 8600
          name: dns
          protocol: UDP
        env:
        - name: CONSUL_BIND_INTERFACE
          value: eth0
        command:
          - consul
          - agent
          - -server
          - -bootstrap-expect=3
          - -ui
          - -client=0.0.0.0
          - -data-dir=/consul/data
        volumeMounts:
        - name: consul-data
          mountPath: /consul/data
  volumeClaimTemplates:
  - metadata:
      name: consul-data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 1Gi