apiVersion: v1
kind: Service
metadata:
  name: ${CHAIN_NAME}-node
  namespace: crypto-staking
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      name: http
  selector:
    app: ${CHAIN_NAME}-node
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${CHAIN_NAME}-node
  namespace: crypto-staking
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ${CHAIN_NAME}-node
  template:
    metadata:
      labels:
        app: ${CHAIN_NAME}-node
        chain: ${CHAIN_NAME}
    spec:
      containers:
      - name: node-service
        image: node-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: SERVICE_NAME
          value: "${CHAIN_NAME}-node"
        - name: CHAIN_NAME
          value: "${CHAIN_NAME}"
        - name: PORT
          value: "8080"
        - name: CONSUL_ADDR
          value: "http://consul:8500"
        - name: NODE_RPC_URL
          valueFrom:
            secretKeyRef:
              name: blockchain-secrets
              key: ${CHAIN_NAME}-rpc-url
        - name: LOG_LEVEL
          value: "info"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "500m"
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ${CHAIN_NAME}-node-hpa
  namespace: crypto-staking
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ${CHAIN_NAME}-node
  minReplicas: 2
  maxReplicas: 6
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70